final Map<String, String> constantText = {
  "instant_pay": "Instant Pay",
  "tag_line": "Your Perfect Payment Partner",
  "login_headline": "login with your mobile phone number",
  "recieve_money": "Recieve Money",
  "other_options": "Other Options",
  "pay_id": "Your Pay ID",
  "show_bank_details": "Show bank account details",
  "notifications": "Notifications",
  "recent_notifications": "Recent Notifications",
  "search_bar_text": "Search Users,ID’s etc",
  "home_tab": "Home",
  "balance_tab": "Balance",
  "offers_tab": "Offers",
  "rewards_tab": "Rewards",
  "portfolio_value": "Portfolio Value",
};
